#' Make Gene Names Legal Variable Names
#'
#' It is common that gene names are saved as names of rows or columns of an
#' expression matrix. In R, this could create some problems because some gene
#' names are not legal variable names and thus will be converted when they are
#' saved as column names (which R assumes that they should be legal variable
#' names). This automatic confusion might interfere with name matching.
#' \code{normalize_genename()} converts gene names to make them legal variable
#' names, thereby make sure the gene names compared are consistently after
#' conversion. \code{normalize_genename()} will add a prefix (gn_) to gene
#' names to make gene names starting with a number legal, and then calls
#' \code{\link{make.names[base]}()} to convert illegal punctuations.
#' @param gene a character vector containing gene names
#'
#' @return a character vector containing prefixed and converted gene names
#' @seealso \code{\link{denormalize_genename}()}
normalize_genename <- function(gene) {
  # Make gene names legal colnames which can be safely reversed by removing the "gn_" prefix
  genelist <- paste0("gn_", gene)
  genelist <- make.names(genelist, unique = FALSE)
  return(genelist)
}


#' Remove Prefix Added When Making Gene Names Legal Variable Names
#'
#' \code{denormalize_genename()} removes the prefix
#' \code{\link{normalize_genename}()} adds, and make the gene names more
#' readable for humans.
#' @inheritParams normalize_genename
#'
#' @return a character vector containing converted gene names with prefix
#' removed
denormalize_genename <- function(gene) {
  name <- substr(start = 4, stop = nchar(gene), gene)
  return(name)
}


#' Make an Reference for Gene Name Conversion
#'
#' \code{make_database()} loads gene name / ID conversion tables from online
#' databases (e.g., FlyBase) and a user-provided GTF file that is used to
#' annotate the features of the NGS dataset of interest (e.g., the GTF file
#' STAR or \code{cellranger count} uses), and makes conversion tables from the
#' loaded data.
#'
#' @inheritParams prepare_database
#' @return a list containing multiple coversion tables and meta data
#' @export
#'
#' @examples
#' dmeldb <- make_database(species = "dmel",
#'                            gtf.path = "extdata/dummy.gtf")
make_database <- function(species = "dmel", gtf.path, version = NULL) {
  db <- prepare_database(species = species,
                         gtf.path = gtf.path,
                         version = version)

  # Generate conversion vectors from the synonym table
  db <- generate_flybase_sym(db)
  # Generate conversion vectors for FBgn update
  db <- generate_fbid_version_table(db)
  db <- generate_gene_mapping(db)

  return(db)
}


#' Prepare an Unprocessed Database for Gene Name Conversion
#'
#' \code{prepare_database()} loads gene name / ID conversion tables from online
#' databases (e.g., FlyBase) and a user-provided GTF file that is used to
#' annotate the features of the NGS dataset of interest (e.g., the GTF file
#' STAR or \code{cellranger count} uses) into memory for later processing by
#' \code{\link{make_database}()}.
#'
#' @param species a character string describing the species of the genes.
#' (Options: "\code{dmel}")
#' @param gtf.path a character string containing the path to the GTF file
#' containing the input gene names (e.g., the GTF files used by
#' \code{cellranger count})
#' @param version a character specifying the version desired
#' (e.g., "FB2019_01".)
#'
#' @return a list containing data frames and character strings of meta data
prepare_database <- function(species = "dmel", gtf.path, version = NULL) {
  if (!species %in% c("dmel", "test")) {
    stop("prepare_database does not support ", species, " now.")
  }
  # Load GTF file (contains gene id and names)
  id_mapping <- rtracklayer::import(gtf.path)
  id_mapping <- as.data.frame(id_mapping)
  id_mapping <- id_mapping[id_mapping$type == "gene", ]

  # Load data from species-specific gene databases
  if (species == "dmel") {
    result <- fetch_flybase(version = version)
  }

  # Load data from local if in test environment
  if (species == "test") {
    result <- fetch_flybase(paths = c("extdata/dummy_fbgn.tsv",
                                      "extdata/dummy_syno.tsv"))
  }

  # Keep gene id and gene name from the GTF file
  gtf <- id_mapping[ , c("gene_id", "gene_name")]
  result[["gtf"]] <- gtf
  result[["metadata"]] <- c("species" = species,
                            "date" = date(),
                            "GTF_path" = gtf.path,
                            "FlyBase_ver" = version)

  return(result)
}


#' Generate Conversion Tables for Symbols and Aliases to FlyBase ID
#'
#' @param db a list generated by \code{\link{prepare_database}()}
#'
#' @return a list of 2 (a named vector that translate symbols to FB ids and
#' another that translates aliases to FB ids)
generate_flybase_sym <- function(db) {
  # Generate a a named vector for conversion based on Flybase Synonym
  # with which you can use alias/name to query FBid
  # Usage: named_vector <- generate_flybase_sym([the tsv file])
  # named_vector[*alias/name*] gives its corresponding flybase id
  fbsym <- db[["syno"]]

  # Keep only Drosophila genes
  colnames(fbsym)[1] <- "primary_fbid"
  fbsym <- fbsym[fbsym$organism_abbreviation == "Dmel", ]
  fbsym <- fbsym[grepl("^FBgn", fbsym$primary_fbid), ]

  # Generate a named vector with *aliases as names* and
  # *fbid as values*
  alias_dict_list <- list()
  for (row in seq(nrow(fbsym))) {
    alias <- strsplit(fbsym[row, "symbol_synonym(s)"], ",")[[1]]
    if (length(alias) > 0) {
      fbid <- fbsym[row, "primary_fbid"]
      dict <- rep(fbid, length(alias))
      names(dict) <- normalize_genename(alias)
      alias_dict_list[[fbid]] <- dict
    }
  }

  alias_dict <- unlist(alias_dict_list)

  # Since unlist appends names of the list items to names of vector items
  # For example, if ChAT is #10000 in the file, before unlist() the
  # name:value would be ChAT:FBid
  # After unlist it would be 10000.ChAT:FBid
  # I'll remove the list item names (the "10000." part) for they disrupt
  # mapping
  names(alias_dict) <- gsub("^[0-9]*\\.", "", names(alias_dict))

  # Generate a named vector with *symbols as names* and
  # *fbid as values*
  symbol_dict <- fbsym$primary_fbid
  names(symbol_dict) <- normalize_genename(fbsym$current_symbol)

  # Add conversion vectors into db and remove raw data
  db[["symbol_dict"]] <- symbol_dict
  db[["alias_dict"]] <- alias_dict
  db <- db[names(db) != c("syno")]
  return(db)
}


generate_fbid_version_table <- function(db, version) {
  # Read the FBgn annotation table from FlyBase
  id_table <- db[["fbid"]]

  # Report the version used
  if (is.null(version)) {version <- "current"}
  message("Using FlyBase version: ", version, " to update FBgn.")

  # Generate a conversion vector
  query <- id_table$`secondary_FBgn#(s)`
  names(query) <- id_table$`primary_FBgn#`
  lookup <- lapply(names(query), function(x) {
    old_id <- strsplit(query[[x]], split = ",")[[1]]
    if (length(old_id) > 0) {
      result <- rep(x, length(old_id))
      names(result) <- old_id
      return(result)
    }
  }, simplify = FALSE)
  lookup <- lookup[sapply(lookup, function(x) !is.null(x))]
  lookup <- unlist(lookup)

  # Remove raw data and return db with the conversion vector
  db[["id_dict"]] <- lookup
  db <- db[names(db) != "fbid"]
  return(db)
}


#' Generate a Mapping Vector to Translate Gene IDs
#'
#' \code{generate_gene_mapping()} takes gene names from a character vector, an
#' expression matrix / data frame, or a Seurat object, and generate a vector
#' that can be used to translate gene IDs to the gene names provided to
#' \code{generate_gene_mapping()}. The purpose of this translation is to make
#' sure different datasets are consistent in the gene names used during
#' analysis, and to thereby ensure comparsion between datasets or querying are
#' accurate.
#' @param db a list generated by \code{\link{prepare_database}()}
#' @param ... other arguments that are passed to \code{\link{get_gene_names}()}
#' (see below)
#' @inheritParams get_gene_names
#'
#' @return a named character vector, in which the values are gene names and
#' the names are gene ids
generate_gene_mapping <- function(db, ...) {
  # Check if db is legit
  if (!"gtf" %in% names(db)) {
    stop(strwrap("The database list seems to be wrong. Please make sure that
                 you generated it by prepare_database() before using gene
                 name conversion functions."))
  }
  id_mapping <- db[["gtf"]]
  id_update_dict <- db[["id_dict"]]

  # Update FBgn
  if (db[["metadata"]]["species"] %in% c("dmel", "test")) {
    id_mapping$gene_id <- update_fbid(id_mapping$gene_id, db = db)
  }


  # If x is not already a character vector, get gene names from x first
  # if (!is.character(x)) {
    # x <- get_gene_names(x, ...)
  # }

  # Check if there are genes not found in the reference
  # x_found <- x[x %in% id_mapping$gene_name]
  # if (length(x) != length(x_found)) {
    # warning(strwrap("Some gene names are not found in the GTF file.
            # Please check if the version is correct."))
    # message("The genes not seen in the GTF file include: ",
            # paste(setdiff(x, x_found), collapse = ", "),
            # ".")
  # }

  # Only keep the part of GTF that contains the input gene names
  # id_mapping <- id_mapping[id_mapping$gene_name %in% x, ]

  result <- id_mapping$gene_name
  names(result) <- id_mapping$gene_id
  db[["to_name_dict"]] <- result
  db <- db[names(db) != "gtf"]
  return(db)
}


update_fbid <- function (id, db) {
  # Convert out-dated FBid to current version
  ## Load lookup table
  version_dict <- db[["id_dict"]]
  ## Find FBid that need conversion
  index_update <- id %in% names(version_dict)
  ## Convert with lookup table while keeping the order
  result <- sapply(seq(length(id)), function (x) {
    if (index_update[x]) {
      return(version_dict[id[x]])
    }
    return(id[x])
  })
  result <- unname(result)
  return(result)
}



categorize_gene <- function(name, flybase_sym) {
  # Separate gene names to 2 categories
  # 1. Matching current symbol
  # 2. Matching aliases

  ## Remove mitochondrial genes
  name <- name[!grepl("^mt:", name)]
  name <- normalize_genename(name)
  ## Here I suppose that genes with names matching official symbols do not need conversion
  in_symbol <- name[name %in% names(flybase_sym[["symbol"]])]
  names(in_symbol) <- flybase_sym[["symbol"]][in_symbol]
  not_in_symbol <- name[!name %in% names(flybase_sym[["symbol"]])]
  alias <- not_in_symbol[not_in_symbol %in% names(flybase_sym[["alias"]])]
  names(alias) <- flybase_sym[["alias"]][alias]

  ## Create warnings if there's multiple mapping for aliases
  for (item in not_in_symbol) {
    matching_num <- sum(names(flybase_sym[["alias"]]) == item)
    if (matching_num > 1) {
      warning(paste0("'", denormalize_genename(item), "' is matched with multiple aliases. ",
                     "Please check the FB id generated here to determine if the mapping is correct."))
    }
  }

  ## Remind the user about non-convertible gene names
  unmapped <- setdiff(not_in_symbol, alias)
  if (length(unmapped) > 0) {
    unmapped <- paste(unmapped, collapse = ", ")
    warning(paste0("Please note the following genes are not found in the database and won't be processed: ",
                   denormalize_genename(unmapped), "."))
  }
  genelist <- list("symbol" = in_symbol, "alias" = alias)
  return(genelist)
}

convert_fbid <- function(name, flybase_sym) {
  # Convert a list of fly gene to flybase id
  ## Get a list of dataframes with a conversion table with Flybase IDs and symbol/alias
  genelist <- categorize_gene(name, flybase_sym = flybase_sym)
  fbid <- unique(c(names(genelist[["symbol"]]), names(genelist[["alias"]])))
  return(fbid)
}

#' @param x a character vector, a data frame / matrix containing an expression
#' matrix, or a Seurat object
convert_10Xgenename <- function(name, flybase_sym, dict10X) {
  # Convert a list of fly gene names to make it compatible
  # with the 10X gene names in the Seurat object

  ## Generate a named list from the Seurat object
  ## work as a dictionary for conversion

  ## Convert input names to Fbid
  input_fbid <- convert_fbid(name, flybase_sym)
  ## Throw away genes that are not present in 10X
  input_fbid <- input_fbid[input_fbid %in% names(dict_10X)]
  name_10Xformat <- dict_10X[input_fbid]
  name_10Xformat <- normalize_genename(name_10Xformat)
  return(name_10Xformat)
}